# Generated by Django 5.0.2 on 2024-02-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegamer_app', '0002_developer_genre_post_publisher_game_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
    ]
