# Generated by Django 5.0.2 on 2024-02-22 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegamer_app', '0003_alter_game_summary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.CreateModel(
            name='GameDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegamer_app.developer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegamer_app.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(through='thegamer_app.GameDeveloper', to='thegamer_app.developer'),
        ),
    ]
