# Generated by Django 5.0.2 on 2024-02-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thegamer_app', '0004_alter_post_table_gamedeveloper_game_developers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamedeveloper',
            table='game_developers',
        ),
    ]
