# Generated by Django 5.0.2 on 2024-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegamer_app', '0005_alter_gamedeveloper_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='developers',
            field=models.ManyToManyField(through='thegamer_app.GameDeveloper', to='thegamer_app.game'),
        ),
    ]
