# Generated by Django 5.0.2 on 2024-02-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thegamer_app', '0006_developer_developers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='developers',
            new_name='games',
        ),
    ]
