# Generated by Django 5.0.2 on 2024-02-23 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegamer_app', '0007_rename_developers_developer_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegamer_app.game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegamer_app.genre')),
            ],
            options={
                'db_table': 'game_genres',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(through='thegamer_app.GameGenre', to='thegamer_app.genre'),
        ),
        migrations.CreateModel(
            name='GamePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegamer_app.game')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegamer_app.post')),
            ],
            options={
                'db_table': 'game_posts',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='posts',
            field=models.ManyToManyField(through='thegamer_app.GamePost', to='thegamer_app.post'),
        ),
        migrations.CreateModel(
            name='GamePublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegamer_app.game')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegamer_app.publisher')),
            ],
            options={
                'db_table': 'game_publishers',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(through='thegamer_app.GamePublisher', to='thegamer_app.publisher'),
        ),
    ]
