# Generated by Django 5.0.2 on 2024-02-23 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegamer_app', '0008_gamegenre_game_genres_gamepost_game_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(max_length=1028),
        ),
    ]
