# Generated by Django 5.0.2 on 2024-02-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thegamer_app', '0010_post_games_alter_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='games',
        ),
    ]
